# Generated by Django 2.2.6 on 2020-02-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(help_text='Zip-file', upload_to='')),
                ('title', models.CharField(help_text='All uploaded photos will be given a title made up of this title + a sequential number.<br>This field is required if creating a new gallery, but is optional when adding to an existing gallery - if not supplied, the photo titles will be creating from the existing gallery name.', max_length=250, verbose_name='title')),
                ('slug', models.SlugField(help_text='A "slug" is a unique URL-friendly title for an object.', max_length=250, unique=True, verbose_name='slug')),
            ],
        ),
    ]
